const animixstreamKeywords = [
  "Anime",
  "Streaming",
  "Simulcast",
  "Subbed",
  "Dubbed",
  "Watchlist",
  "HD",
  "Episodes",
  "Series",
  "Library",
  "Subtitles",
  "Community",
  "Recommendations",
  "Mobile",
  "Multi-device",
  "Ad-free",
  "Premium",
  "Engaging",
  "Vibrant",
  "Adventure",
  "Action",
  "Fantasy",
  "Sci-fi",
  "Romance",
  "Comedy",
  "Shonen",
  "Shojo",
  "Seinen",
  "Josei",
  "Popular",
  "Hidden gems",
  "Japanese animation",
  "Animation",
  "Latest releases",
  "Classic anime",
  "Thrilling",
  "Intuitive interface",
  "Exclusive content",
  "Social features",
  "Discussion forums",
  "High-quality visuals",
  "Captivating characters",
  "Diverse genres",
  "Interactive",
  "Uninterrupted viewing",
  "Ongoing series",
  "Fan community",
  "Engrossing plots",
  "Top-rated",
  "Immersive experience",
];

export default animixstreamKeywords;
