// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface TopAiring {
    currentPage: number;
    hasNextPage: boolean;
    results:     Result[];
}

export interface Result {
    id:     string;
    title:  string;
    image:  string;
    url:    string;
    genres: string[];
}
