// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface RecentEp {
    currentPage: string;
    hasNextPage: boolean;
    results:     Result[];
}

export interface Result {
    id:            string;
    episodeId:     string;
    episodeNumber: number;
    title:         string;
    image:         string;
    url:           string;
}
